name: CI
on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]
jobs:
  test:
    name: runner/test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: run test
        run: go test -v ./...
